Repository scientific-python/changelist, pull requests merged in 2023-07, with the labels that each got.

#1 Use label-check and attach-next-milestone-action
  .github/workflows/label-check.yaml
  .github/workflows/milestone-merged-prs.yaml
Labels: maintenance

#2 Fix example usage
  README.md
Labels: type: Documentation

#3 Pre commit
  .git-blame-ignore-revs
  .github/workflows/lint.yml
  .gitignore
  .pre-commit-config.yaml
  README.md
  pyproject.toml
  src/changelist/__main__.py
Labels: type: Maintenance

#4 Use dependabot
  .github/dependabot.yml
Labels: type: Maintenance

#6 Specify label for dependabot PRs
  .github/dependabot.yml
Labels: type: Maintenance

#7 Document label and milestone actions
  README.md
Labels: type: Documentation

#9 Only print non-empty sections
  src/changelist/__main__.py
Labels: type: Enhancement

#10 Fix for linters
  src/changelist/__main__.py
Labels: type: Enhancement

#11 Document release process
  RELEASE.md
Labels: type: Documentation

#13 Update README
  README.md
Labels: type: Documentation

#14 Improve release process
  RELEASE.md
Labels: type: Documentation

#20 Refactor into submodules
  src/changelist/__main__.py
  src/changelist/_cli.py
  src/changelist/_format.py
  src/changelist/_query.py
Labels: type: Maintenance
