Repository scientific-python/changelist, pull requests merged in 2023-09, with the labels that each got.

#27 Remove newlines between pull request summaries and their links
  src/changelist/_format.py
Labels: type: Enhancement

#28 Format contributor section as lists
  src/changelist/_format.py
Labels: type: Bug fix

#33 Update README
  README.md
Labels: type: Maintenance

#35 Add newline after PR sections
  src/changelist/_format.py
Labels: type: Bug fix

#36 Link to example in README
  README.md
Labels: type: Documentation

#40 Add newline before lists in contributor section
  src/changelist/_format.py
Labels: type: Enhancement
