Repository scientific-python/changelist, pull requests merged in 2023-10, with the labels that each got.

#30 Add project specific configuration via local or remote `pyproject.toml`
  MANIFEST.in
  README.md
  src/changelist/_cli.py
  src/changelist/_config.py
  src/changelist/_format.py
  src/changelist/default_config.toml
Labels: type: Enhancement

#44 Add docstrings to `_config.py` submodule
  src/changelist/_config.py
Labels: type: Documentation

#48 Use trusted publisher
  .github/workflows/release.yml
  RELEASE.md
Labels: type: Maintenance

#43 Ensure README is synched with code
  .pre-commit-config.yaml
  .tools/readme.py
  README.md
Labels: type: Documentation, type: Maintenance

#50 Add newline after release title
  src/changelist/_format.py
Labels: type: Bug fix
